In [1]:
from numpy import *

In [2]:
a = array((1,2,3,4,5))
a

array([1, 2, 3, 4, 5])

In [5]:
row1 = (1,2,3)
row2 = (3,4,5)

In [6]:
(row1, row2)

((1, 2, 3), (3, 4, 5))

In [ ]:
try:
    import numpy as N
    import pygame.surfarray as surfarray
except ImportError:
    raise ImportError("NumPy and Surfarray are required.")

pygame 2.6.1 (SDL 2.28.4, Python 3.13.12)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [19]:
import numpy as N
import pygame 
import sys

def surfdemo_show(array_data, title="Array Preview"):


    pygame.init()

    width, height = array_data.shape[0], array_data.shape[1]
    screen = pygame.display.set_mode((width, height ))
    pygame.display.set_caption(title)


    if len(array_data.shape) == 2:

        surf = pygame.surfarray.make_surface(array_data)
    else:
        surf = pygame.surfarray.make_surface(array_data)

    screen.blit(surf, (0,0))
    pygame.display.flip()

    print(f"Showing {title} window. Close the Pygame window to continue ...")
    running = True
    while running: 
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
    pygame.quit()



In [17]:

allblack = N.zeros((128, 128))
surfdemo_show(allblack, 'allblack')

Showing allblack window. Close the Pygame window to continue ...


In [7]:
class Cell:
    def __init__(self, posx, posy):
        self.x = posx
        self.y = posy
        self.alive = True

    def scan_moore(self) -> bool:
        pass

In [65]:
import numpy as np
import time
import random

class Grid:
    def __init__(self, size):
        self.size = size
        self.grid = [['0'] * self.size[0] for _ in range(self.size[1])]
        

    def create_cell(self):
        """
        Generates a 2D List array as a grid where the cells  will be alive or dead. 
        """
        posx = np.random.randint(0, self.size[0])
        print(f"Creating cell at position {posx}")
        posy = np.random.randint(0, self.size[1])
        print(f"Creating a cell at position {posx}, {posy}")

        self.grid[posx][posy] = '*'

    def show_grid(self):
        print(len(self.grid))
        for i in self.grid:
            for j in i:
                 time.sleep(0.0001)
                 print(f'{j}', end=' ')

            time.sleep(0.0002)
            print('\t')
            

In [ ]:
g = Grid((10, 10))
g.show_grid()
time.sleep(2)
g.create_cell()
g.show_grid()
g.create_cell()
g.show_grid()
g.create_cell()
g.show_grid()


10
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
Creating cell at position 5
Creating a cell at position 5, 3
10
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 * 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
Creating cell at position 6
Creating a cell at position 6, 6
10
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 * 0 0 0 0 0 0 	
0 0 0 0 0 0 * 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
Creating cell at position 3
Creating a cell at position 3, 0
10
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
* 0 0 0 0 0 0 0 0 0 	
0 0 0 0 0 0 0 0 0 0 	
0 0 0 * 0 0 0 0 0 0 	
0 0 0 0 0 0 *

: 

In [28]:
print([[0] * 10])

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


In [1]:
import numpy as np

In [22]:
x = np.array([[1,2,3],[4,5,6]], dtype=np.int32)

In [63]:
x.nbytes

24

In [64]:
board = np.zeros(shape=(10,10), dtype=np.int8)

In [65]:
print(board)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [66]:
ypos= np.random.randint(low=0, high=board.shape[0])
xpos = np.random.randint(low=0,high=board.shape[1])
print(ypos)
print(xpos)
board[xpos][ypos] = 1

8
5


In [67]:
board

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [68]:
left = np.roll(board, shift=1, axis=1)
right = np.roll(board, shift=-1, axis=1)
top = np.roll(board, shift=1, axis=0)
down = np.roll(board, shift=-1, axis=0)


In [69]:
# This function will be vectorized so that it can be broadcasted across all elements. 
def moore_nb(x,y,b):
    # Sequence goes top,a nd moves anti-clockwise
    n_count = 0
    nbrs  = [(x-1,y), (x-1,y-1),(x,y-1), (x+1,y-1),(x+1,y),(x+1,y+1),(x,y+1),(x-1,y+1)]
    for (ix,iy) in nbrs:
        if 0<=ix < b.shape[0] and 0<= iy < b.shape[1]:
            if b[ix][iy] == 1:
                n_count +=1

    return n_count
        

In [70]:
moore_nb_vec = np.vectorize(moore_nb, excluded=[2])

In [71]:
neighbor_matrix = np.fromfunction(lambda x,y: moore_nb_vec(x,y,board),shape=(10, 10), dtype=int)

In [72]:
neighbor_matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# Filters

birth_condition = (neighbor_matrix == 3)
survival_mask = (neighbor_matrix == 2) | (neighbor_matrix == 3)
next_board = np.zeros_like(board)
next_board[(board == 0) & birth_condition] = 1
next_board[(board==1) & survival_mask] == 1
board = next_board

In [75]:
board

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)